# Generated by Django 6.0.4 on 2026-05-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('MANAGER', 'Менеджер'), ('VIEWER', 'Наблюдатель'), ('CONTRACTOR', 'Исполнитель'), ('DISPATCHER', 'Диспетчер')], default='VIEWER', max_length=10, verbose_name='Роль'),
        ),
    ]
