# Generated by Django 6.0.4 on 2026-05-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_convert_roles_and_remove_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='extra_permissions',
            field=models.ManyToManyField(blank=True, db_table='users_profile_extra_permissions', related_name='user_extra', to='auth.permission', verbose_name='Дополнительные права'),
        ),
        migrations.AddField(
            model_name='profile',
            name='restricted_permissions',
            field=models.ManyToManyField(blank=True, db_table='users_profile_restricted_permissions', related_name='user_restricted', to='auth.permission', verbose_name='Запрещённые права (имеют приоритет)'),
        ),
    ]
