# Generated by Django 6.0.4 on 2026-05-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_extra_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='extra_permissions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='restricted_permissions',
        ),
    ]
