# Generated by Django 6.0.4 on 2026-06-20 07:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (CSS класс)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория имущества',
                'verbose_name_plural': 'Категории имущества',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(help_text='Уникальный инвентарный номер (генерируется автоматически)', max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата приобретения')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость (руб.)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Местонахождение')),
                ('status', models.CharField(choices=[('in_use', 'В эксплуатации'), ('in_stock', 'На складе'), ('under_repair', 'В ремонте'), ('written_off', 'Списано'), ('lost', 'Утеряно')], default='in_stock', max_length=20, verbose_name='Статус')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='asset_qr/', verbose_name='QR-код')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_assets', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Имущество',
                'verbose_name_plural': 'Имущество',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата закрепления')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assets.asset')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Кому закреплено')),
            ],
            options={
                'verbose_name': 'Закрепление имущества',
                'verbose_name_plural': 'Закрепления имущества',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата проверки')),
                ('condition', models.CharField(choices=[('good', 'Хорошее'), ('needs_repair', 'Требует ремонта'), ('damaged', 'Повреждено'), ('written_off', 'Списано')], default='good', max_length=20, verbose_name='Состояние')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='assets.asset')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_checks', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Проверка имущества',
                'verbose_name_plural': 'Проверки имущества',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAsset',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('inventory_number', models.CharField(db_index=True, help_text='Уникальный инвентарный номер (генерируется автоматически)', max_length=50, verbose_name='Инвентарный номер')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата приобретения')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость (руб.)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Местонахождение')),
                ('status', models.CharField(choices=[('in_use', 'В эксплуатации'), ('in_stock', 'На складе'), ('under_repair', 'В ремонте'), ('written_off', 'Списано'), ('lost', 'Утеряно')], default='in_stock', max_length=20, verbose_name='Статус')),
                ('qr_code', models.TextField(blank=True, max_length=100, null=True, verbose_name='QR-код')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.assetcategory', verbose_name='Категория')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible_person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'historical Имущество',
                'verbose_name_plural': 'historical Имущество',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['inventory_number'], name='assets_asse_invento_8d6625_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_asse_status_347ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['responsible_person'], name='assets_asse_respons_6abfed_idx'),
        ),
    ]
