# Generated by Django 6.0.4 on 2026-06-20 08:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='useful_life_months',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите срок полезного использования в месяцах', null=True, verbose_name='Срок полезного использования, мес.'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='useful_life_months',
            field=models.PositiveIntegerField(blank=True, help_text='Укажите срок полезного использования в месяцах', null=True, verbose_name='Срок полезного использования, мес.'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory', verbose_name='Балансовый счет'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Балансовая стоимость (руб.)'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='inventory_number',
            field=models.CharField(help_text='Уникальный инвентарный номер (вводится вручную)', max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assets.assetcategory', verbose_name='Балансовый счет'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Балансовая стоимость (руб.)'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='inventory_number',
            field=models.CharField(db_index=True, help_text='Уникальный инвентарный номер (вводится вручную)', max_length=50, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию'),
        ),
    ]
