# Generated by Django 6.0.4 on 2026-06-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_useful_life_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='imported_from_excel',
            field=models.BooleanField(default=False, help_text='Отметка, что запись была создана при импорте из Excel', verbose_name='Импортировано из Excel'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='imported_from_excel',
            field=models.BooleanField(default=False, help_text='Отметка, что запись была создана при импорте из Excel', verbose_name='Импортировано из Excel'),
        ),
    ]
