# Generated by Django 6.0.4 on 2026-06-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_add_imported_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='inventory_number',
            field=models.CharField(blank=True, help_text='Оставьте пустым для автоматической генерации', max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='inventory_number',
            field=models.CharField(blank=True, db_index=True, help_text='Оставьте пустым для автоматической генерации', max_length=50, verbose_name='Инвентарный номер'),
        ),
    ]
