# Generated by Django 6.0.4 on 2026-06-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_make_inventory_number_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='asset_photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='photo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Фото'),
        ),
    ]
