# Generated by Django 6.0.4 on 2026-06-21 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_photo_historicalasset_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='asset_photos/', verbose_name='Основное фото'),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='photo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Основное фото'),
        ),
        migrations.CreateModel(
            name='AssetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='asset_gallery/', verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='assets.asset', verbose_name='Имущество')),
            ],
            options={
                'verbose_name': 'Фото имущества',
                'verbose_name_plural': 'Фотографии имущества',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
