# Generated by Django 6.0.4 on 2026-04-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='room_number',
            field=models.CharField(default='', max_length=20, verbose_name='Номер помещения'),
            preserve_default=False,
        ),
    ]
