# Generated by Django 6.0.4 on 2026-04-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='is_active',
        ),
        migrations.AddField(
            model_name='material',
            name='quantity_in_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='usedmaterial',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Наименование'),
        ),
    ]
