# Generated by Django 6.0.4 on 2026-04-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0005_alter_material_options_remove_material_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='time_spent',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Затраченное время (минуты)'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='track_time',
            field=models.BooleanField(default=False, verbose_name='Учитывать время выполнения'),
        ),
    ]
