# Generated by Django 6.0.4 on 2026-04-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0006_servicerequest_time_spent_servicerequest_track_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('closed', 'Закрыта'), ('suspended', 'Приостановлена')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
