# Generated by Django 6.0.4 on 2026-04-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0007_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина приостановки'),
        ),
    ]
