# Generated by Django 6.0.4 on 2026-05-03 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0009_requestfile_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedmaterial',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='requests_app.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='usedmaterial',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usedmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usedmaterial',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_materials', to='requests_app.servicerequest'),
        ),
        migrations.AlterField(
            model_name='usedmaterial',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
