# Generated by Django 6.0.4 on 2026-05-03 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0010_usedmaterial_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests_app.material', verbose_name='Материал'),
        ),
    ]
