# Generated by Django 6.0.4 on 2026-05-04 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0012_requesthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfile',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='requestfile',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='requests_app.servicerequest', verbose_name='Файлы'),
        ),
    ]
