# Generated by Django 6.0.4 on 2026-05-05 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0013_requestfile_description_alter_requestfile_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='requests_app.servicerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Назначенный исполнитель',
                'verbose_name_plural': 'Назначенные исполнители',
                'unique_together': {('request', 'user')},
            },
        ),
    ]
