# Generated by Django 6.0.4 on 2026-05-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0014_requestassignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
    ]
