# Generated by Django 6.0.4 on 2026-05-31 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_add_building_volumes'),
        ('requests_app', '0015_servicerequest_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.buildingsection', verbose_name='Часть здания'),
        ),
    ]
