# Generated by Django 6.0.4 on 2026-05-31 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_add_building_volumes'),
        ('requests_app', '0016_add_section_to_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.building', verbose_name='Здание по умолчанию для новых заявок')),
            ],
            options={
                'verbose_name': 'Настройки заявок',
                'verbose_name_plural': 'Настройки заявок',
            },
        ),
    ]
