# Generated by Django 6.0.4 on 2026-05-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0017_add_request_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsettings',
            name='single_building',
            field=models.BooleanField(default=False, help_text='Если включено, поле выбора здания скрывается, и все заявки создаются только для здания по умолчанию', verbose_name='Единственное здание'),
        ),
    ]
