# Generated by Django 6.0.4 on 2026-06-17 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_add_building_volumes'),
        ('requests_app', '0018_add_single_building_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', 'created_at'], name='requests_ap_status_bb4ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['assigned_to', 'status'], name='requests_ap_assigne_b354e3_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['planned_date', 'status'], name='requests_ap_planned_950ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['building', 'created_at'], name='requests_ap_buildin_cbf8d0_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['priority'], name='requests_ap_priorit_61175a_idx'),
        ),
    ]
