# Generated by Django 6.0.4 on 2026-06-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0019_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='requests_ap_status_bb4ff0_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='requests_ap_assigne_b354e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='requests_ap_planned_950ce0_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='requests_ap_buildin_cbf8d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='requests_ap_priorit_61175a_idx',
        ),
    ]
