# Generated by Django 6.0.4 on 2026-06-24 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_add_building_volumes'),
        ('requests_app', '0020_make_created_at_editable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('in', 'Поступление'), ('out', 'Списание'), ('return', 'Возврат')], max_length=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Транзакция материала',
                'verbose_name_plural': 'Транзакции материалов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Счётчик номеров заявок',
                'verbose_name_plural': 'Счётчики номеров заявок',
            },
        ),
        migrations.AlterField(
            model_name='requestfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='request_files/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status'], name='requests_ap_status_fa6e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['priority'], name='requests_ap_priorit_61175a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['created_at'], name='requests_ap_created_e7751d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['planned_date'], name='requests_ap_planned_98b387_idx'),
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='requests_app.material'),
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requests_app.servicerequest'),
        ),
    ]
