# Generated by Django 6.0.4 on 2026-06-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0022_auto_20260624_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Минимальный остаток'),
        ),
    ]
