# Generated by Django 6.0.4 on 2026-05-24 18:39

import buildings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_alter_building_id_alter_buildingdocument_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='balance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Балансовая стоимость (млн руб.)'),
        ),
        migrations.AddField(
            model_name='building',
            name='design_capacity',
            field=models.CharField(blank=True, max_length=200, verbose_name='Проектная мощность'),
        ),
        migrations.AddField(
            model_name='building',
            name='director_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО руководителя'),
        ),
        migrations.AddField(
            model_name='building',
            name='director_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон руководителя'),
        ),
        migrations.AddField(
            model_name='building',
            name='floors_desc',
            field=models.TextField(blank=True, verbose_name='Междуэтажные и чердачное перекрытия'),
        ),
        migrations.AddField(
            model_name='building',
            name='foundation_desc',
            field=models.TextField(blank=True, verbose_name='Фундаменты'),
        ),
        migrations.AddField(
            model_name='building',
            name='frame_desc',
            field=models.TextField(blank=True, verbose_name='Несущий каркас'),
        ),
        migrations.AddField(
            model_name='building',
            name='has_color_palette',
            field=models.BooleanField(default=False, verbose_name='Колористический паспорт'),
        ),
        migrations.AddField(
            model_name='building',
            name='has_kkr_project',
            field=models.BooleanField(default=False, verbose_name='Проект ККР'),
        ),
        migrations.AddField(
            model_name='building',
            name='has_landscaping_project',
            field=models.BooleanField(default=False, verbose_name='Проект благоустройства'),
        ),
        migrations.AddField(
            model_name='building',
            name='has_tzk',
            field=models.BooleanField(default=False, verbose_name='ТЗК'),
        ),
        migrations.AddField(
            model_name='building',
            name='institution_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Наименование учреждения'),
        ),
        migrations.AddField(
            model_name='building',
            name='other_documentation',
            field=models.TextField(blank=True, verbose_name='Прочая документация'),
        ),
        migrations.AddField(
            model_name='building',
            name='project_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип проекта'),
        ),
        migrations.AddField(
            model_name='building',
            name='roof_cover_desc',
            field=models.TextField(blank=True, verbose_name='Кровля (водоизолирующий слой)'),
        ),
        migrations.AddField(
            model_name='building',
            name='roof_structure_desc',
            field=models.TextField(blank=True, verbose_name='Несущие элементы кровли'),
        ),
        migrations.AddField(
            model_name='building',
            name='stairs_desc',
            field=models.TextField(blank=True, verbose_name='Лестницы'),
        ),
        migrations.AddField(
            model_name='building',
            name='territory_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь прилегающей территории (м²)'),
        ),
        migrations.AddField(
            model_name='building',
            name='walls_desc',
            field=models.TextField(blank=True, verbose_name='Стены и перегородки'),
        ),
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buildingdocument',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='buildings.building'),
        ),
        migrations.AlterField(
            model_name='buildingdocument',
            name='file',
            field=models.FileField(upload_to='building_documents/%Y/%m/%d/', validators=[buildings.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='buildingdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='buildingdocument',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='buildingdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='BuildingAppendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appendix_type', models.CharField(choices=[('geobase', 'Геоподоснова'), ('bti_plan', 'Планы БТИ'), ('explication', 'Экспликация'), ('other', 'Другое')], max_length=20, verbose_name='Тип приложения')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='building_appendixes/%Y/%m/', validators=[buildings.models.validate_pdf], verbose_name='Файл (PDF)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendixes', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Приложение',
                'verbose_name_plural': 'Приложения',
            },
        ),
        migrations.CreateModel(
            name='BuildingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('roof', 'Кровля'), ('premises', 'Помещения'), ('floor', 'Полы')], max_length=20, verbose_name='Тип площади')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование (тип покрытия/помещения)')),
                ('area', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Площадь (м²)')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Площадь здания',
                'verbose_name_plural': 'Площади здания',
            },
        ),
        migrations.CreateModel(
            name='BuildingInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Дата проверки')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Причина проверки')),
                ('inspector', models.CharField(max_length=200, verbose_name='ФИО, должность проверяющего')),
                ('findings', models.TextField(verbose_name='Основные замечания, № предписания')),
                ('conclusion', models.TextField(blank=True, verbose_name='Заключение')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Проверка',
                'verbose_name_plural': 'Проверки',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='BuildingLandscaping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=200, verbose_name='Элемент благоустройства')),
                ('quantity', models.CharField(blank=True, max_length=100, verbose_name='Кол-во, площадь, длина')),
                ('characteristic', models.CharField(blank=True, max_length=200, verbose_name='Характеристика')),
                ('has_documents', models.BooleanField(default=False, verbose_name='Наличие паспортов/сертификатов')),
                ('condition', models.CharField(blank=True, max_length=200, verbose_name='Состояние')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landscaping', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Элемент благоустройства',
                'verbose_name_plural': 'Благоустройство территории',
            },
        ),
        migrations.CreateModel(
            name='BuildingRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=200, verbose_name='Объект ремонта')),
                ('repair_type', models.CharField(max_length=100, verbose_name='Вид ремонта')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('contract_number', models.CharField(blank=True, max_length=50, verbose_name='№ контракта')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Сумма контракта (руб.)')),
                ('contractor', models.CharField(blank=True, max_length=200, verbose_name='Наименование организации')),
                ('warranty_period', models.CharField(blank=True, max_length=100, verbose_name='Гарантийный срок')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Ремонт',
                'verbose_name_plural': 'Ремонты',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BuildingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(choices=[('basement', 'Подвал'), ('1', '1 этаж'), ('2', '2 этаж'), ('3', '3 этаж'), ('4', '4 этаж'), ('5', '5 этаж'), ('technical', 'Технический этаж'), ('attic', 'Чердак')], max_length=20, verbose_name='Этаж')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование помещения')),
                ('ceiling_finish', models.CharField(blank=True, max_length=200, verbose_name='Потолок')),
                ('walls_finish', models.CharField(blank=True, max_length=200, verbose_name='Стены')),
                ('floors_finish', models.CharField(blank=True, max_length=200, verbose_name='Полы')),
                ('windows', models.CharField(blank=True, max_length=200, verbose_name='Окна')),
                ('doors', models.CharField(blank=True, max_length=200, verbose_name='Двери')),
                ('last_repair_type', models.CharField(blank=True, max_length=100, verbose_name='Вид ремонта')),
                ('last_repair_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год последнего ремонта')),
                ('condition', models.CharField(blank=True, max_length=100, verbose_name='Общее состояние')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендации')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Внутреннее помещение',
                'verbose_name_plural': 'Внутренние помещения',
            },
        ),
        migrations.CreateModel(
            name='BuildingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('heating', 'Теплоснабжение'), ('hot_water', 'ГВС'), ('cold_water', 'ХВС'), ('sewerage', 'Водоотведение и канализация'), ('electricity', 'Электроснабжение'), ('ventilation', 'Вентиляция'), ('fire', 'Противопожарные системы'), ('security', 'Охранные системы'), ('comms', 'Сети связи и локальные сети'), ('other', 'Прочие коммуникации')], max_length=20, verbose_name='Тип системы')),
                ('system_type_other', models.CharField(blank=True, max_length=100, verbose_name="Другое (если 'Прочие')")),
                ('type_desc', models.CharField(blank=True, max_length=200, verbose_name='Тип системы (описание)')),
                ('power', models.CharField(blank=True, max_length=100, verbose_name='Мощность (Гкал/ч, кВт и т.п.)')),
                ('inlet_diameter', models.CharField(blank=True, max_length=50, verbose_name='Диаметр ввода')),
                ('district_number', models.CharField(blank=True, max_length=50, verbose_name='№ района')),
                ('district_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон района')),
                ('subscriber_number', models.CharField(blank=True, max_length=50, verbose_name='№ абонента')),
                ('meter1_type', models.CharField(blank=True, max_length=50, verbose_name='Тип счётчика (1)')),
                ('meter1_number', models.CharField(blank=True, max_length=50, verbose_name='№ счётчика (1)')),
                ('meter1_verification_date', models.DateField(blank=True, null=True, verbose_name='Дата очередной поверки (1)')),
                ('meter2_type', models.CharField(blank=True, max_length=50, verbose_name='Тип счётчика (2)')),
                ('meter2_number', models.CharField(blank=True, max_length=50, verbose_name='№ счётчика (2)')),
                ('meter2_verification_date', models.DateField(blank=True, null=True, verbose_name='Дата очередной поверки (2)')),
                ('meter3_type', models.CharField(blank=True, max_length=50, verbose_name='Тип счётчика (3)')),
                ('meter3_number', models.CharField(blank=True, max_length=50, verbose_name='№ счётчика (3)')),
                ('meter3_verification_date', models.DateField(blank=True, null=True, verbose_name='Дата очередной поверки (3)')),
                ('network_description', models.TextField(blank=True, verbose_name='Краткая характеристика сети')),
                ('last_repair_type', models.CharField(blank=True, max_length=100, verbose_name='Вид ремонта')),
                ('last_repair_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год последнего ремонта')),
                ('installed_power', models.CharField(blank=True, max_length=100, verbose_name='Мощность установленная (кВт) (для электроснабжения)')),
                ('permitted_power', models.CharField(blank=True, max_length=100, verbose_name='Мощность разрешенная (кВт) (для электроснабжения)')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Инженерная система',
                'verbose_name_plural': 'Инженерные системы',
            },
        ),
        migrations.CreateModel(
            name='BuildingTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование арендатора')),
                ('activity', models.CharField(blank=True, max_length=200, verbose_name='Вид деятельности')),
                ('rented_areas', models.CharField(blank=True, max_length=200, verbose_name='Арендуемая площадь (номера помещений)')),
                ('lease_term', models.CharField(blank=True, max_length=100, verbose_name='Срок аренды')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='Номер договора аренды')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Арендатор',
                'verbose_name_plural': 'Арендаторы',
            },
        ),
    ]
