# Generated by Django 6.0.5 on 2026-05-30 08:05

import buildings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_building_balance_cost_building_design_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Название здания'),
        ),
        migrations.AlterField(
            model_name='buildingappendix',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendixes', to='buildings.building', verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='buildingappendix',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='buildingarea',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='buildings.building', verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='buildingdocument',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='buildings.building', verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='buildingdocument',
            name='file',
            field=models.FileField(upload_to='building_documents/%Y/%m/%d/', validators=[buildings.models.validate_pdf], verbose_name='Файл документа (PDF)'),
        ),
        migrations.AlterField(
            model_name='buildingdocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='buildingdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='buildinginspection',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='buildings.building', verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='buildinglandscaping',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landscaping', to='buildings.building', verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='buildingrepair',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='buildings.building', verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='buildingroom',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='buildings.building', verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='buildingsystem',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='buildings.building', verbose_name='Здание'),
        ),
        migrations.AlterField(
            model_name='buildingtenant',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='buildings.building', verbose_name='Здание'),
        ),
        migrations.CreateModel(
            name='BuildingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название части здания')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_common', models.BooleanField(default=False, verbose_name='Общая (относится ко всему зданию)')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='buildings.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Часть здания',
                'verbose_name_plural': 'Части здания',
                'ordering': ['order', 'name'],
                'unique_together': {('building', 'name')},
            },
        ),
        migrations.AddField(
            model_name='buildingappendix',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.buildingsection', verbose_name='Часть здания'),
        ),
        migrations.AddField(
            model_name='buildingarea',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.buildingsection', verbose_name='Часть здания'),
        ),
        migrations.AddField(
            model_name='buildingdocument',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.buildingsection', verbose_name='Часть здания'),
        ),
        migrations.AddField(
            model_name='buildinginspection',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.buildingsection', verbose_name='Часть здания'),
        ),
        migrations.AddField(
            model_name='buildinglandscaping',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.buildingsection', verbose_name='Часть здания'),
        ),
        migrations.AddField(
            model_name='buildingrepair',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.buildingsection', verbose_name='Часть здания'),
        ),
        migrations.AddField(
            model_name='buildingroom',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.buildingsection', verbose_name='Часть здания'),
        ),
        migrations.AddField(
            model_name='buildingsystem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.buildingsection', verbose_name='Часть здания'),
        ),
        migrations.AddField(
            model_name='buildingtenant',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.buildingsection', verbose_name='Часть здания'),
        ),
    ]
