# Generated by Django 6.0.5 on 2026-05-30 09:16

import buildings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_alter_building_name_alter_buildingappendix_building_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='has_kkr_project',
        ),
        migrations.RemoveField(
            model_name='building',
            name='has_landscaping_project',
        ),
        migrations.RemoveField(
            model_name='building',
            name='has_tzk',
        ),
        migrations.RemoveField(
            model_name='building',
            name='other_documentation',
        ),
        migrations.CreateModel(
            name='BuildingOwnershipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='building_ownership_docs/%Y/%m/', validators=[buildings.models.validate_pdf], verbose_name='Файл (PDF)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_docs', to='buildings.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Документ о собственности',
                'verbose_name_plural': 'Документы о собственности',
            },
        ),
    ]
