# Generated by Django 6.0.5 on 2026-05-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_remove_building_has_kkr_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='design_capacity',
        ),
        migrations.RemoveField(
            model_name='building',
            name='has_color_palette',
        ),
        migrations.RemoveField(
            model_name='building',
            name='wall_material',
        ),
    ]
