# Generated by Django 6.0.5 on 2026-05-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_remove_wall_material_design_capacity_color_palette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='foundation_type',
        ),
    ]
