# Generated by Django 6.0.5 on 2026-05-30 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_remove_foundation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='residential_livable_area',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Жилая площадь (комнаты, м²)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='non_residential_area',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Площадь нежилых помещений (м²)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='residential_area',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Общая площадь жилых помещений (м²)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_area',
            field=models.FloatField(editable=False, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Общая площадь здания (м²)'),
        ),
    ]
