# Generated by Django 6.0.4 on 2026-05-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_add_residential_livable_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='demolition_decision',
            field=models.TextField(blank=True, verbose_name='Решение о сносе'),
        ),
        migrations.AddField(
            model_name='building',
            name='emergency_info',
            field=models.TextField(blank=True, verbose_name='Сведения об аварийности'),
        ),
        migrations.AddField(
            model_name='building',
            name='is_cultural_heritage',
            field=models.BooleanField(default=False, verbose_name='Объект культурного наследия'),
        ),
        migrations.AddField(
            model_name='building',
            name='major_repair_decision',
            field=models.TextField(blank=True, verbose_name='Решение о капитальном ремонте'),
        ),
        migrations.AddField(
            model_name='building',
            name='underground_floors',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество подземных этажей'),
        ),
    ]
