# Generated by Django 6.0.4 on 2026-05-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_add_passport_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Объем здания (м³)'),
        ),
        migrations.AddField(
            model_name='building',
            name='underground_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Объем подземной части (м³)'),
        ),
    ]
