# Generated by Django 6.0.4 on 2026-04-25 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип ресурса')),
                ('unit', models.CharField(max_length=10, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Тип ресурса',
                'verbose_name_plural': 'Типы ресурсов',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название счётчика')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Местоположение')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='Серийный номер')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('transformation_ratio', models.DecimalField(decimal_places=3, default=1.0, help_text='Для электроэнергии (трансформаторы). Для воды и тепла оставьте 1.', max_digits=10, verbose_name='Коэффициент трансформации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.resourcetype', verbose_name='Тип ресурса')),
            ],
            options={
                'verbose_name': 'Счётчик',
                'verbose_name_plural': 'Счётчики',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата показания')),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Показание (суммарное)')),
                ('consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Потребление')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.meter', verbose_name='Счётчик')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
                'ordering': ['-date'],
                'unique_together': {('meter', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TariffComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название компонента')),
                ('unit', models.CharField(blank=True, max_length=10, verbose_name='Единица (оставьте пустой, чтобы брать из ресурса)')),
                ('is_multi_tariff_zone', models.BooleanField(default=False, verbose_name='Является зоной дня/ночи?')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.resourcetype', verbose_name='Тип ресурса')),
            ],
            options={
                'verbose_name': 'Компонент тарифа',
                'verbose_name_plural': 'Компоненты тарифов',
                'ordering': ['resource_type', 'name', '-valid_from'],
                'unique_together': {('resource_type', 'name', 'valid_from')},
            },
        ),
        migrations.CreateModel(
            name='ZoneReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Показание по зоне')),
                ('consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Потребление по зоне')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_readings', to='energy.reading')),
                ('tariff_component', models.ForeignKey(limit_choices_to={'is_multi_tariff_zone': True}, on_delete=django.db.models.deletion.CASCADE, to='energy.tariffcomponent')),
            ],
        ),
    ]
