# Generated by Django 6.0.4 on 2026-04-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='default_tariff1_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Тариф Т1 по умолчанию (руб/ед)'),
        ),
        migrations.AddField(
            model_name='meter',
            name='default_tariff2_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Тариф Т2 по умолчанию (руб/ед)'),
        ),
        migrations.AddField(
            model_name='meter',
            name='default_tariff3_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Тариф Т3 по умолчанию (руб/ед)'),
        ),
        migrations.AddField(
            model_name='meter',
            name='is_unregulated_tariff',
            field=models.BooleanField(default=False, help_text='Если активно, при вводе показаний потребуется вручную указывать тарифы. Если нет – используются тарифы по умолчанию.', verbose_name='Нерегулируемый тариф'),
        ),
    ]
