# Generated by Django 6.0.4 on 2026-04-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='is_multi_tariff',
            field=models.BooleanField(default=False, help_text='Отметьте, если счётчик поддерживает разные тарифы по зонам (день/ночь/пик)', verbose_name='Многотарифный счётчик'),
        ),
    ]
