# Generated by Django 6.0.4 on 2026-04-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_meter_default_tariff1_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='is_unregulated_tariff',
            field=models.BooleanField(default=False, help_text='Если активно, при вводе показаний потребуется вручную указывать тарифы.', verbose_name='Нерегулируемый тариф'),
        ),
    ]
