# Generated by Django 6.0.4 on 2026-04-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_meter_is_multi_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='initial_value',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Для однотарифных счётчиков. Будет вычтено из первого показания.', max_digits=12, verbose_name='Начальное показание'),
        ),
        migrations.CreateModel(
            name='InitialZoneReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Начальное показание')),
                ('meter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initial_zone_readings', to='energy.meter')),
                ('tariff_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.tariffcomponent')),
            ],
            options={
                'verbose_name': 'Начальное показание по зоне',
                'verbose_name_plural': 'Начальные показания по зонам',
                'unique_together': {('meter', 'tariff_component')},
            },
        ),
    ]
