# Generated by Django 6.0.4 on 2026-04-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_meter_initial_value_initialzonereading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='name',
        ),
        migrations.AlterField(
            model_name='meter',
            name='serial_number',
            field=models.CharField(max_length=50, verbose_name='Серийный номер / Название счётчика'),
        ),
    ]
