# Generated by Django 6.0.4 on 2026-04-25 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_remove_meter_name_alter_meter_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='initial_value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Начальное показание'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='is_multi_tariff',
            field=models.BooleanField(default=False, verbose_name='Многотарифный счётчик'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='transformation_ratio',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=10, verbose_name='Коэффициент трансформации'),
        ),
        migrations.CreateModel(
            name='MeterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='meter_documents/%Y/%m/%d/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='energy.meter', verbose_name='Счётчик')),
            ],
            options={
                'verbose_name': 'Документ счётчика',
                'verbose_name_plural': 'Документы счётчиков',
            },
        ),
    ]
