# Generated by Django 6.0.4 on 2026-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0005_alter_meter_initial_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterdocument',
            name='title',
        ),
        migrations.AddField(
            model_name='meterdocument',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Описание'),
        ),
    ]
