# Generated by Django 6.0.4 on 2026-04-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0006_remove_meterdocument_title_meterdocument_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='user',
        ),
    ]
