# Generated by Django 6.0.4 on 2026-04-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0007_remove_user_from_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='heat_loss_coefficient',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Для тепла (например, 1.05). Для других ресурсов оставьте 1.0.', max_digits=5, verbose_name='Коэффициент теплопотерь'),
        ),
        migrations.AddField(
            model_name='meter',
            name='sewerage_coefficient',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Для воды (обычно 1.0). Если водоотведение равно 0.8, укажите 0.8.', max_digits=5, verbose_name='Коэффициент водоотведения'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='initial_value',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Для однотарифных счётчиков. Будет вычтено из первого показания.', max_digits=12, verbose_name='Начальное показание'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='is_multi_tariff',
            field=models.BooleanField(default=False, help_text='Отметьте, если счётчик поддерживает разные тарифы по зонам (день/ночь/пик)', verbose_name='Многотарифный счётчик'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Серийный номер / Название счётчика'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='transformation_ratio',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Для электроэнергии (трансформаторы). Для воды и тепла оставьте 1.', max_digits=10, verbose_name='Коэффициент трансформации'),
        ),
    ]
