# Generated by Django 6.0.4 on 2026-04-26 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0008_meter_heat_loss_coefficient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='heat_loss_coefficient',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='sewerage_coefficient',
        ),
    ]
