# Generated by Django 6.0.4 on 2026-04-26 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0009_remove_meter_heat_loss_coefficient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('EDIT', 'Редактирование'), ('DELETE', 'Удаление'), ('VIEW', 'Просмотр'), ('IMPORT', 'Импорт'), ('EXPORT', 'Экспорт'), ('LOGIN', 'Вход'), ('LOGOUT', 'Выход')], max_length=20, verbose_name='Действие')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID объекта')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог пользователя',
                'verbose_name_plural': 'Логи пользователей',
                'ordering': ['-timestamp'],
            },
        ),
    ]
