# Generated by Django 6.0.4 on 2026-04-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0010_userlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата показания')),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Показание (суммарное)')),
                ('consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Потребление')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата архивации')),
                ('meter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='energy.meter', verbose_name='Счётчик')),
            ],
            options={
                'verbose_name': 'Архивное показание',
                'verbose_name_plural': 'Архивные показания',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedZoneReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Показание по зоне')),
                ('consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Потребление по зоне')),
                ('archived_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_readings', to='energy.archivedreading')),
                ('tariff_component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='energy.tariffcomponent')),
            ],
        ),
    ]
