# Generated by Django 6.0.4 on 2026-04-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_alter_meter_is_unregulated_tariff'),
        ('energy', '0011_archivedreading_archivedzonereading'),
    ]

    operations = [
    ]
