# Generated by Django 6.0.4 on 2026-04-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0012_merge_20260426_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='default_tariff1_rate',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='default_tariff2_rate',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='default_tariff3_rate',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='is_unregulated_tariff',
        ),
    ]
