# Generated by Django 6.0.4 on 2026-05-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0013_remove_meter_default_tariff1_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='reset_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего сброса начальных показаний'),
        ),
    ]
