# Generated by Django 6.0.4 on 2026-06-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0014_meter_reset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedreading',
            name='meter_serial',
            field=models.CharField(blank=True, max_length=50, verbose_name='Серийный номер счётчика'),
        ),
    ]
