# Generated by Django 6.0.4 on 2026-06-08 18:26

import energy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0015_archivedreading_meter_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='document',
            field=models.FileField(blank=True, help_text='Максимум 5 МБ. Разрешены JPG, PNG, GIF, BMP, PDF.', null=True, upload_to='reading_documents/%Y/%m/%d/', validators=[energy.models.validate_reading_document], verbose_name='Документ (фото, скан, PDF)'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='reset_date',
            field=models.DateField(blank=True, help_text='С этой даты потребление считается от новых начальных показаний (для нового прибора).', null=True, verbose_name='Дата сброса (замены прибора)'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Потребление (рассчитывается автоматически)'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Показание (суммарное) – для однотарифных счётчиков'),
        ),
    ]
