# Generated by Django 6.0.4 on 2026-06-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0016_reading_document_alter_meter_reset_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialzonereading',
            options={'verbose_name': 'Начальное показание по зоне (устаревшее)', 'verbose_name_plural': 'Начальные показания по зонам (устаревшие)'},
        ),
        migrations.AlterField(
            model_name='initialzonereading',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Начальное показание (устаревшее)'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='initial_value',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Для однотарифных счётчиков. Это поле устарело, используйте историю начальных показаний.', max_digits=12, verbose_name='Начальное показание (устаревшее, используется история)'),
        ),
        migrations.CreateModel(
            name='InitialValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Начальное показание')),
                ('date_from', models.DateField(verbose_name='Действует с')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_value_history', to='energy.meter', verbose_name='Счётчик')),
            ],
            options={
                'verbose_name': 'История начального показания',
                'verbose_name_plural': 'История начальных показаний',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='InitialZoneValueHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Начальное показание по зоне')),
                ('date_from', models.DateField(verbose_name='Действует с')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_zone_value_history', to='energy.meter', verbose_name='Счётчик')),
                ('tariff_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.tariffcomponent', verbose_name='Тарифный компонент (зона)')),
            ],
            options={
                'verbose_name': 'История начального показания по зоне',
                'verbose_name_plural': 'История начальных показаний по зонам',
                'ordering': ['-date_from'],
                'unique_together': {('meter', 'tariff_component', 'date_from')},
            },
        ),
    ]
