# Generated by Django 6.0.4 on 2026-06-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0018_migrate_initial_values_to_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='is_technical',
            field=models.BooleanField(default=False, help_text='Показания этого счётчика не учитываются в общих отчётах и статистике.', verbose_name='Технический учёт'),
        ),
    ]
